name: life-tracker
region: nyc

services:
  - name: web
    # Build from Dockerfile
    dockerfile_path: Dockerfile
    
    # Instance configuration
    instance_count: 1
    instance_size_slug: basic-xxs
    
    # HTTP configuration
    http_port: 3000
    
    # Environment variables
    envs:
      - key: NODE_ENV
        value: production
      - key: PORT
        scope: RUN_TIME
        value: "3000"
    
    # Health check
    health_check:
      http_path: /api/init
      initial_delay_seconds: 10
      period_seconds: 10
      timeout_seconds: 5
      success_threshold: 1
      failure_threshold: 3
    
    # Routes
    routes:
      - path: /
